# Performance Alerting Configuration

performance_alerting:
  enabled: true
  default_cooldown_minutes: 15
  max_alerts_per_hour: 100

# Default alert rules for performance monitoring
alert_rules:
  # CPU usage alerts
  - rule_id: "cpu_high_usage"
    name: "High CPU Usage"
    description: "CPU usage exceeds 85%"
    alert_type: "resource_threshold"
    metric_name: "cpu_percent"
    component: "system"
    threshold_value: 85.0
    comparison_operator: ">"
    severity: "medium"
    enabled: true
    cooldown_minutes: 10

  - rule_id: "cpu_critical_usage"
    name: "Critical CPU Usage"
    description: "CPU usage exceeds 95%"
    alert_type: "resource_threshold"
    metric_name: "cpu_percent"
    component: "system"
    threshold_value: 95.0
    comparison_operator: ">"
    severity: "high"
    enabled: true
    cooldown_minutes: 5

  # Memory usage alerts
  - rule_id: "memory_high_usage"
    name: "High Memory Usage"
    description: "Memory usage exceeds 85%"
    alert_type: "resource_threshold"
    metric_name: "memory_percent"
    component: "system"
    threshold_value: 85.0
    comparison_operator: ">"
    severity: "medium"
    enabled: true
    cooldown_minutes: 10

  - rule_id: "memory_critical_usage"
    name: "Critical Memory Usage"
    description: "Memory usage exceeds 95%"
    alert_type: "resource_threshold"
    metric_name: "memory_percent"
    component: "system"
    threshold_value: 95.0
    comparison_operator: ">"
    severity: "high"
    enabled: true
    cooldown_minutes: 5

  # Disk usage alerts
  - rule_id: "disk_high_usage"
    name: "High Disk Usage"
    description: "Disk usage exceeds 90%"
    alert_type: "resource_threshold"
    metric_name: "disk_percent"
    component: "system"
    threshold_value: 90.0
    comparison_operator: ">"
    severity: "medium"
    enabled: true
    cooldown_minutes: 30

  - rule_id: "disk_critical_usage"
    name: "Critical Disk Usage"
    description: "Disk usage exceeds 95%"
    alert_type: "resource_threshold"
    metric_name: "disk_percent"
    component: "system"
    threshold_value: 95.0
    comparison_operator: ">"
    severity: "high"
    enabled: true
    cooldown_minutes: 15

  # Response time alerts
  - rule_id: "slow_response_time"
    name: "Slow Response Time"
    description: "Application response time exceeds 2 seconds"
    alert_type: "performance_degradation"
    metric_name: "response_time_ms"
    component: "application"
    threshold_value: 2000.0
    comparison_operator: ">"
    severity: "medium"
    enabled: true
    cooldown_minutes: 10

  - rule_id: "very_slow_response_time"
    name: "Very Slow Response Time"
    description: "Application response time exceeds 5 seconds"
    alert_type: "performance_degradation"
    metric_name: "response_time_ms"
    component: "application"
    threshold_value: 5000.0
    comparison_operator: ">"
    severity: "high"
    enabled: true
    cooldown_minutes: 5

  # Database query time alerts
  - rule_id: "slow_database_query"
    name: "Slow Database Query"
    description: "Database query time exceeds 500ms"
    alert_type: "performance_degradation"
    metric_name: "query_time_ms"
    component: "database"
    threshold_value: 500.0
    comparison_operator: ">"
    severity: "medium"
    enabled: true
    cooldown_minutes: 10

  - rule_id: "very_slow_database_query"
    name: "Very Slow Database Query"
    description: "Database query time exceeds 1 second"
    alert_type: "performance_degradation"
    metric_name: "query_time_ms"
    component: "database"
    threshold_value: 1000.0
    comparison_operator: ">"
    severity: "high"
    enabled: true
    cooldown_minutes: 5

  # Trading operation alerts
  - rule_id: "slow_order_processing"
    name: "Slow Order Processing"
    description: "Order processing time exceeds 1 second"
    alert_type: "performance_degradation"
    metric_name: "order_processing_ms"
    component: "trading"
    threshold_value: 1000.0
    comparison_operator: ">"
    severity: "high"
    enabled: true
    cooldown_minutes: 5

  - rule_id: "slow_signal_generation"
    name: "Slow Signal Generation"
    description: "Signal generation time exceeds 500ms"
    alert_type: "performance_degradation"
    metric_name: "signal_generation_ms"
    component: "trading"
    threshold_value: 500.0
    comparison_operator: ">"
    severity: "medium"
    enabled: true
    cooldown_minutes: 10

  # Error rate alerts
  - rule_id: "high_error_rate"
    name: "High Error Rate"
    description: "Application error rate exceeds 5%"
    alert_type: "performance_degradation"
    metric_name: "error_rate_percent"
    component: "application"
    threshold_value: 5.0
    comparison_operator: ">"
    severity: "high"
    enabled: true
    cooldown_minutes: 5

  # Network performance alerts
  - rule_id: "high_network_latency"
    name: "High Network Latency"
    description: "Network latency exceeds 100ms"
    alert_type: "performance_degradation"
    metric_name: "network_latency_ms"
    component: "system"
    threshold_value: 100.0
    comparison_operator: ">"
    severity: "medium"
    enabled: true
    cooldown_minutes: 15

# Anomaly detection settings
anomaly_detection:
  enabled: true
  cpu_anomaly_threshold: 95.0
  memory_anomaly_threshold: 95.0
  response_time_anomaly_threshold: 5000.0
  query_time_anomaly_threshold: 1000.0

# Regression detection settings
regression_detection:
  enabled: true
  regression_threshold: 0.2  # 20% degradation
  baseline_period_hours: 168  # 1 week
  min_samples_for_regression: 20

# Trend analysis settings
trend_analysis:
  enabled: true
  trend_window_hours: 24
  min_samples_for_trend: 10
  trend_confidence_threshold: 0.7

# Alert notification settings
notifications:
  email:
    enabled: true
    recipients: ["admin@grodt.com", "devops@grodt.com"]
    high_severity_only: false
  
  telegram:
    enabled: true
    chat_id: "-1001234567890"
    high_severity_only: true
  
  slack:
    enabled: false
    webhook_url: ""
    channel: "#alerts"
    high_severity_only: true

# Alert suppression settings
suppression:
  enabled: true
  maintenance_windows:
    - start: "02:00"
      end: "04:00"
      timezone: "UTC"
      days: ["saturday", "sunday"]
  
  # Suppress alerts during known high-load periods
  high_load_periods:
    - start: "09:30"
      end: "16:00"
      timezone: "UTC"
      days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
      suppress_severities: ["low", "medium"]
