# Robinhood API Configuration
# Replace with your actual keys from Robinhood App > Settings > API Trading

api:
  key: "your_api_key_here"  # Your Robinhood API key
  private_key: "your_private_key_here"  # Your private key (base64 encoded)
  public_key: "your_public_key_here"  # Your public key (base64 encoded)
  base_url: "https://trading.robinhood.com"
  
# Rate limiting settings
rate_limit:
  delay_ms: 500  # 500ms between requests
  max_retries: 3
  
# Data settings
data:
  default_interval: "1m"
  max_bars_per_request: 1000
