# Application Settings
# This file contains the main configuration for the trading system

# Execution Handler Configuration
# Determines which broker/execution handler to use
execution:
  handler: alpaca_paper  # Options: alpaca_paper, robinhood_live

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/trading.log"

# Data Configuration
data:
  storage_path: "data"
  backup_enabled: true
  backup_interval: "1h"

# Risk Management
risk:
  max_position_size: 0.1  # 10% of portfolio
  stop_loss_percentage: 0.05  # 5% stop loss
  take_profit_percentage: 0.15  # 15% take profit

# Strategy Configuration
strategy:
  enabled: true
  rebalance_interval: "1h"
  max_trades_per_day: 10